version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  api:
    build: . #/ExpressCRUD -- Add this if used on root together with LabCrudRobots
    ports:
    - "3000:3000"
    depends_on:
    - mongo
    - redis
  # Also add this if used on root together with LabCrudRobots
  # web:
  #   build: ./LabCrudRobots
  #   ports:
  #   - "8000:80"
  #   links:
  #   - api